### PR TITLE
Fix #6, #15, #18  + Display temperature on server status

### LINKED ISSUE #6: Can't save changes in config
Get the following error after editing the config and trying to save 

TypeError: Cannot read property 'length' of undefined

### PR DESCRIPTION
**Pull request by shidevil**
- Updated with config settings
need to update config.json or default would be /sys/class/thermal/thermal_zone0/temp

- when new config save, backup config are now timestamp with YYYY-MM-DD-HH:MM:SS 

- Fix #6 

- Fix when adding an accessory/platform and deleting it would not allow to save as an message would prompt "each platform must have a name"

### CODE REVIEW

**Comment by shidevil** [comment]
Fixed #6

**Comment by shidevil** [comment]
Update config.js for platform and accessory .hide() to .remove() due to the following message appearing after deleting the accessory. 


screen shot 2017-08-11 at 2 47 44 am

**Comment by shidevil** [comment]
Fix #15 issue. If no internet connection or when NPM api is down, login is still possible.

User are able to fix this by editing the npm.js file at line 135. Do compare and test it out

**Comment by marcol123** [comment]
Where are the files I have to modify on my filesystem? I cant´t find the npm.js file.

**Comment by shidevil** [comment]
@marcol123 it's in the node_modules/homebridge-config-ui folder

depending on where your node_modules is....

**Comment by marcol123** [comment]
Ok. Found the npm.js and modified it. But this didn´t solve the problem with Issue #15. Are there any other files I have to modify.

**Comment by shidevil** [comment]
@marcol123 could you show me ur modified npm.js? also possible to do a debug=* homebridge

thank you

**Comment by shidevil** [comment]
Change the layout of status homebridge after login for mobile site 
screen shot 2017-08-16 at 4 41 22 pm

**Comment by shidevil** [comment]
update plugin.js from npm.uninstall to npm.install. Tried debugging the /install for platforms it seems that from req.body.platform_json was undefined. 

It would be better to allow "add platform" as when searching for npm, if the npm is a homebridge accessories and not a platform, it couldn't install because platform is not filled up.

Could @mkellsy look into this?

**Comment by shidevil** [comment]
Fix for #18 

changes the fs.appendfile from root:root to <user:user> depending on UID/GID as once changes made on config-ui would not be able to edit via Graphical editor on raspberry pi/debian.  

Also fix that if uninstall does not create additional square brackets in config.json thus preventing it from homebridge to run.

Problem: When adding accessories plugin. Platform have to be totally remove including Open Brace { and close brace } to be able to add successfully. Will see if there is a fix to this, by creating a button just like "add accessory" to install

another problem is when uninstall, the lines in config.json will require manual delete. will look into this if possible

screen shot 2017-08-19 at 3 35 15 am

**Comment by shidevil** [comment]
Updated search input form and optimise the UI for mobile site. 

screen shot 2017-08-19 at 11 19 29 pm
screen shot 2017-08-19 at 11 19 33 pm

**Comment by shidevil** [comment]
fix #20 - remove + "private" from npm.js fix it.

**Comment by shidevil** [comment]
Thanks to @RienduPre for #21 
update #23 
Updated #15

**Comment by shidevil** [comment]
added base path to config as different system have different base path for node_modules.

**Comment by Bankaifan** [comment]
@shidevil The installmethod you updated in the README does not work for me. 
Have a look:

pi@homebridge:~ $ git clone https://github.com/shidevil/homebridge-config-ui.git
Klone nach 'homebridge-config-ui' ...
remote: Counting objects: 1103, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1103 (delta 6), reused 10 (delta 4), pack-reused 1089
Empfange Objekte: 100% (1103/1103), 1.75 MiB | 1.22 MiB/s, Fertig.
Löse Unterschiede auf: 100% (752/752), Fertig.

pi@homebridge:~ $ cd homebridge-config-ui/

pi@homebridge:~/homebridge-config-ui $ sudo npm install -g
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN checkPermissions Missing write access to /home/pi/homebridge-config-ui/node_modules/statuses
npm WARN checkPermissions Missing write access to /home/pi/homebridge-config-ui/node_modules
npm ERR! path /home/pi/homebridge-config-ui/node_modules/statuses
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/home/pi/homebridge-config-ui/node_modules/statuses'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-11-08T13_12_03_133Z-debug.log

pi@homebridge:~/homebridge-config-ui $ sudo cat /root/.npm/_logs/2017-11-08T13_12_03_133Z-debug.log
439 warn checkPermissions Missing write access to /home/pi/homebridge-config-ui/node_modules/statuses
440 warn checkPermissions Missing write access to /home/pi/homebridge-config-ui/node_modules
441 verbose stack Error: ENOENT: no such file or directory, access '/home/pi/homebridge-config-ui/node_modules/statuses'
442 verbose cwd /home/pi/homebridge-config-ui
443 verbose Linux 4.9.60-v7+
444 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g"
445 verbose node v8.9.0
446 verbose npm  v5.5.1
447 error path /home/pi/homebridge-config-ui/node_modules/statuses
448 error code ENOENT
449 error errno -2
450 error syscall access
451 error enoent ENOENT: no such file or directory, access '/home/pi/homebridge-config-ui/node_modules/statuses'
452 error enoent This is related to npm not being able to find a file.
453 verbose exit [ -2, true ]


EDIT: Shortened the log

**Comment by shidevil** [comment]
Will update it. Sorry I think I forgot to add something let me check

**Comment by mgibeau** [comment]
Any plans to have this merged some time? Otherwise I would propose to fork the repo and publish the changes to npm under a different name?

**Pull request merged**
